"""Дополнительный словарь перевода нот — длинный хвост (редкие/специфичные ингредиенты)."""

NOTES_EXTRA_RU = {
    "taif rose": "роза таиф",
    "champagne": "шампанское",
    "brown sugar": "коричневый сахар",
    "resin": "смола",
    "oud": "уд",
    "lime (linden) blossom": "цветок липы",
    "tincture of rose": "настойка розы",
    "rice": "рис",
    "cucumber": "огурец",
    "mastic or lentisque": "мастика (лентиск)",
    "moroccan rose": "марокканская роза",
    "akigalawood": "акигалавуд",
    "cannabis": "конопля",
    "carambola (star fruit)": "карамбола",
    "cotton flower": "цветок хлопка",
    "toffee": "тоффи",
    "guatemalan cardamom": "гватемальский кардамон",
    "pistachio": "фисташка",
    "sicilian mandarin": "сицилийский мандарин",
    "grapes": "виноград",
    "tomato leaf": "лист томата",
    "indian oud": "индийский уд",
    "wisteria": "глициния",
    "wild strawberry": "лесная земляника",
    "grasse rose": "роза грасс",
    "papaya": "папайя",
    "mineral notes": "минеральные ноты",
    "tahitian vanilla": "таитянская ваниль",
    "iris flower": "цветок ириса",
    "dates": "финики",
    "fern": "папоротник",
    "tonka": "тонка",
    "white lily": "белая лилия",
    "rose oil": "масло розы",
    "frankincense": "ладан (босвеллия)",
    "chestnut": "каштан",
    "animal notes": "анималистические ноты",
    "lemon blossom": "цветок лимона",
    "cambodian oud": "камбоджийский уд",
    "rose water": "розовая вода",
    "black amber": "чёрная амбра",
    "peppermint": "перечная мята",
    "sand": "песок",
    "ginger flower": "цветок имбиря",
    "absinthe": "полынь (абсент)",
    "sorbet": "сорбет",
    "white chocolate": "белый шоколад",
    "verbena": "вербена",
    "sugar cane": "сахарный тростник",
    "lemongrass": "лемонграсс",
    "crystal amber": "кристальная амбра",
    "civetta": "цивета",
    "patchouli leaf": "лист пачули",
    "laotian oud": "лаосский уд",
    "bourbon geranium": "бурбонская герань",
    "fennel": "фенхель",
    "black vanilla husk": "чёрный стручок ванили",
    "rhuburb": "ревень",
    "gin": "джин",
    "tunisian neroli": "тунисский нероли",
    "fir resin": "пихтовая смола",
    "lemon zest": "цедра лимона",
    "brazilian orange": "бразильский апельсин",
    "broom": "ракитник (дрок)",
    "coconut nectar": "кокосовый нектар",
    "calone": "калон",
    "ylang ylang": "иланг-иланг",
    "red rose": "красная роза",
    "metallic notes": "металлические ноты",
    "pear blossom": "цветок груши",
    "palo santo": "пало санто",
    "tuscan iris": "тосканский ирис",
    "vanilla bean": "стручок ванили",
    "java vetiver oil": "масло яванского ветивера",
    "indian tuberose": "индийская тубероза",
    "water jasmine": "водный жасмин",
    "paprika": "паприка",
    "texas cedar": "техасский кедр",
    "wild rose": "дикая роза",
    "green accord": "зелёный аккорд",
    "tobacco blossom": "цветок табака",
    "rose hip": "шиповник",
    "clover": "клевер",
    "banana": "банан",
    "yellow mandarin": "жёлтый мандарин",
    "carrot": "морковь",
    "earthy notes": "землистые ноты",
    "pine needles": "хвоя сосны",
    "vanilla flower": "цветок ванили",
    "exotic woods": "экзотическая древесина",
    "hinoki wood": "дерево хиноки",
    "natural musk": "натуральный мускус",
    "exotic fruits": "экзотические фрукты",
    "olive tree": "оливковое дерево",
    "cedar needles": "кедровая хвоя",
    "tropical fruits": "тропические фрукты",
    "black rose": "чёрная роза",
    "tunisian orange blossom": "тунисский цветок апельсина",
    "cardamon": "кардамон",
    "night blooming jasmine": "ночной жасмин",
    "liquor": "ликёр",
    "cashmere musk": "кашемировый мускус",
    "ceylon cinnamon": "цейлонская корица",
    "tea rose": "чайная роза",
    "syringa": "сирень (сиринга)",
    "blood mandarin": "кровавый мандарин",
    "sesame": "кунжут",
    "oregano": "орегано",
    "wildflowers": "полевые цветы",
    "bourbon vetiver": "бурбонский ветивер",
    "datura": "дурман",
    "mirabelle": "мирабель",
    "marjoram": "майоран",
    "tulip": "тюльпан",
    "plum blossom": "цветок сливы",
    "fig tree": "инжирное дерево",
    "mandarin leaf": "лист мандарина",
    "dew drop": "капля росы",
    "oriental notes": "восточные ноты",
    "currant buds": "почки смородины",
    "cashmirwood": "кашемировое дерево",
    "water hyacinth": "водный гиацинт",
    "almond milk": "миндальное молоко",
    "coconut water": "кокосовая вода",
    "black orchid": "чёрная орхидея",
    "ebony": "чёрное дерево (эбен)",
    "spanish labdanum": "испанский лабданум",
    "bamboo leaf": "лист бамбука",
    "walnut": "грецкий орех",
    "agarwood": "агаровое дерево",
    "birch leaf": "лист берёзы",
    "orange peel": "апельсиновая цедра",
    "birch tar": "берёзовый дёготь",
    "candy apple": "карамельное яблоко",
    "mexican chocolate": "мексиканский шоколад",
    "grapefruit blossom": "цветок грейпфрута",
    "laurels": "лавр",
    "black musk": "чёрный мускус",
    "pine tree needles": "хвоя сосны",
    "pitahaya": "питахая",
    "black locust": "белая акация",
    "sunflower": "подсолнух",
    "chili pepper": "перец чили",
    "red wine": "красное вино",
    "ice": "лёд",
    "white iris": "белый ирис",
    "green grass": "зелёная трава",
    "litsea cubeba": "литсея кубеба",
    "ebony wood": "чёрное дерево (эбен)",
    "raspberry leaf": "лист малины",
    "turmeric": "куркума",
    "vodka": "водка",
    "palmarosa": "пальмароза",
    "ambrette": "амбретта",
    "copaiba balm": "копайский бальзам",
    "shiso": "шисо",
    "amaryllis": "амариллис",
    "black currant leaf": "лист чёрной смородины",
    "pitosporum": "питтоспорум",
    "tamarind": "тамаринд",
    "lemon leaf": "лист лимона",
    "palm leaf": "пальмовый лист",
    "acácia": "акация",
    "vanilla pod": "стручок ванили",
    "cactus": "кактус",
    "cade oil": "кадовое масло",
    "sandal": "сандал",
    "star jasmine": "звёздчатый жасмин",
    "green pepper": "зелёный перец",
    "mandarin blossom": "цветок мандарина",
    "african geranium": "африканская герань",
    "white tobacco": "белый табак",
    "black currant blossom": "цветок чёрной смородины",
    "pink freesia": "розовая фрезия",
    "copahu balm": "копаловый бальзам",
    "night blooming cereus": "ночной кактус (цереус)",
    "truffle": "трюфель",
    "petitgrain paraguay": "петитгрейн парагвай",
    "white sandalwood": "белый сандал",
    "red pepper": "красный перец",
    "priprioca": "приприока",
    "ebony tree": "чёрное дерево",
    "dry wood": "сухая древесина",
    "red cedar": "красный кедр",
    "balsamic notes": "бальзамические ноты",
    "red thyme": "красный тимьян",
    "maple": "клён",
    "poppy": "мак",
    "cactus flower": "цветок кактуса",
    "chinese osmanthus": "китайский османтус",
    "skin": "кожа (skin)",
    "calamus": "аир",
    "sicilian orange": "сицилийский апельсин",
    "tahitian vetiver": "таитянский ветивер",
    "singapore patchouli": "сингапурская пачули",
    "camellia": "камелия",
    "hyrax": "гиракс",
    "dried plum": "сушёная слива (чернослив)",
    "dahlia": "георгин",
    "sequoia": "секвойя",
    "macarons": "макарон",
    "madagascar vetiver": "мадагаскарский ветивер",
    "pelargonium": "пеларгония",
    "butter": "сливочное масло",
    "clearwood": "клирвуд",
    "blackcurrant syrup": "сироп чёрной смородины",
    "madagascar pepper": "мадагаскарский перец",
    "acai berry": "ягода асаи",
    "aromatic spices": "ароматные специи",
    "red peony": "красный пион",
    "camelia": "камелия",
    "buchu or agathosma": "бучу (агатосма)",
    "tea leaf": "чайный лист",
    "daisy": "маргаритка",
    "fig nectar": "инжирный нектар",
    "nard himalayan (jatamansi)": "гималайский нард (джатаманси)",
    "apricot blossom": "цветок абрикоса",
    "mojito": "мохито",
    "cupcake": "капкейк",
    "soil tincture": "настойка земли",
    "cistus incanus": "ладанник",
    "spun sugar": "сахарная нить",
    "fenugreek": "пажитник",
    "bellflower": "колокольчик",
    "lemon peel": "лимонная цедра",
    "black violet": "чёрная фиалка",
    "wheat": "пшеница",
    "celery seeds": "семена сельдерея",
    "accord eudora®": "аккорд eudora®",
    "thailand oud": "тайский уд",
    "costus": "костус",
    "red chilli pepper": "красный чили",
    "blue lotus": "голубой лотос",
    "exotic floral notes": "экзотические цветочные ноты",
    "roasted coffee beans": "жареные кофейные зёрна",
    "lavender extract": "экстракт лаванды",
    "ambrarome": "амбраром",
    "cinammon": "корица",
    "brandy": "бренди",
    "violet root": "корень фиалки",
    "sweet almond": "сладкий миндаль",
    "nashi pear": "груша наши",
    "white suede": "белая замша",
    "amaretto": "амаретто",
    "popcorn": "попкорн",
    "custard": "заварной крем",
    "black cherry": "чёрная вишня",
    "white oud": "белый уд",
    "rock rose": "ладанник (rock rose)",
    "indian patchouli": "индийская пачули",
    "mignonette": "резеда",
    "lemon tree": "лимонное дерево",
    "coca-cola": "кока-кола",
    "allspice": "ямайский перец",
    "wild orchid": "дикая орхидея",
    "pink rose": "розовая роза",
    "malt": "солод",
    "marine notes": "морские ноты",
    "pineapple leaf": "лист ананаса",
    "stephanotis": "стефанотис",
    "silk tree blossom": "цветок альбиции (шёлкового дерева)",
    "mountain air": "горный воздух",
    "tahitian tiare flower": "таитянский цветок тиаре",
    "liatris": "лиатрис",
    "moroccan cedar": "марокканский кедр",
    "gooseberry": "крыжовник",
    "ink": "чернила",
    "blood grapefruit": "кровавый грейпфрут",
    "white orchid": "белая орхидея",
    "holly": "падуб",
    "cetalox": "цеталокс",
    "camphor": "камфора",
    "cinnamon leaf": "лист корицы",
    "white currant": "белая смородина",
    "marzipan": "марципан",
    "aloe vera": "алоэ вера",
    "maltol": "мальтол",
    "white grapefruit": "белый грейпфрут",
    "celery": "сельдерей",
    "japanese cherry blossom": "японская сакура",
    "jasmine tea": "жасминовый чай",
    "dark woodsy notes": "тёмные древесные ноты",
    "matcha tea": "матча",
    "casablanca lily": "лилия касабланка",
    "white violet": "белая фиалка",
    "petalia": "петалия",
    "turkey red rose": "турецкая красная роза",
    "himalayan cedar": "гималайский кедр",
    "orange leaf": "лист апельсина",
    "mace": "мускатный цвет",
    "black elder": "чёрная бузина",
    "ice cream": "мороженое",
    "cascalone": "каскалон",
    "almond tree": "миндальное дерево",
    "spruce": "ель",
    "gentiana": "горечавка",
    "rose geranium": "розовая герань",
    "cappuccino": "капучино",
    "russian leather": "русская кожа",
    "mahonial": "маонал",
    "black": "чёрный",
    "italian iris": "итальянский ирис",
    "milk mousse": "молочный мусс",
    "italian jasmine": "итальянский жасмин",
    "lime (linden blossom)": "цветок липы",
    "berry fruits": "ягоды",
    "green almond": "зелёный миндаль",
    "mirabelle plum": "слива мирабель",
    "orcanox™": "орканокс™",
    "arum lily": "аронник (калла)",
    "earl grey tea": "чай эрл грей",
    "black cardamom": "чёрный кардамон",
    "yellow freesia": "жёлтая фрезия",
    "gingerbread": "имбирный пряник",
    "dreamwood": "дримвуд",
    "apple tree": "яблоня",
    "mangosteen": "мангостин",
    "hortensia": "гортензия",
    "west indian bay": "вест-индский лавр",
    "aromatic notes": "ароматные ноты",
    "raspberry bloom": "цветение малины",
    "turkish rose oil": "масло турецкой розы",
    "nasturtium": "настурция",
    "creme brulee": "крем-брюле",
    "indonesian nutmeg": "индонезийский мускатный орех",
    "parma violet": "пармская фиалка",
    "mexican vanilla": "мексиканская ваниль",
    "algae": "водоросли",
    "neroli essence": "эссенция нероли",
    "pink lotus": "розовый лотос",
    "tropical fruit": "тропический фрукт",
    "caviar": "икра",
    "ambrettolide": "амбреттолид",
    "lorenox": "лоренокс",
    "dewberry": "ежевика (dewberry)",
    "italian orris root": "итальянский корень ириса",
    "tyger lily": "тигровая лилия",
    "italian orange": "итальянский апельсин",
    "madagascar ylang-ylang": "мадагаскарский иланг-иланг",
    "piña colada": "пина колада",
    "graperfuit": "грейпфрут",
    "bourbon pepper": "бурбонский перец",
    "bran": "отруби",
    "candied almond": "засахаренный миндаль",
    "candied fruits": "цукаты",
    "oily notes": "маслянистые ноты",
    "rhubarb leaf": "лист ревеня",
    "siberian pine": "сибирская сосна",
    "marshamallow": "зефир",
    "cabreuva": "кабрева",
    "pink tulip": "розовый тюльпан",
    "hibiscus seed": "семена гибискуса",
    "calabrian mandarin": "калабрийский мандарин",
    "bitter orange blossom": "цветок горького апельсина",
    "red poppy": "красный мак",
    "damask plum": "дамасская слива",
    "magnolia petals": "лепестки магнолии",
    "black fig": "чёрный инжир",
    "mango blossom": "цветок манго",
    "false jasmine": "ложный жасмин (гельземиум)",
    "seagrass": "морская трава",
    "kashmir wood": "кашмирское дерево",
    "paradisone": "парадизон",
    "blackwood": "чёрное дерево",
    "pink jasmine": "розовый жасмин",
    "amyl salicylate": "амилсалицилат",
    "asafoetida": "асафетида",
    "water fruit": "водный фрукт",
    "grenadine": "гренадин",
    "water mint": "водная мята",
    "pataqueira": "патакейра",
    "nutmeg flower": "цветок мускатного ореха",
    "meringue": "меренга (безе)",
    "red lily": "красная лилия",
    "snowdrops": "подснежники",
    "chrysanthemum": "хризантема",
    "forest fruits": "лесные ягоды",
    "amber xtreme": "амбер экстрим",
    "mysore sandalwood": "майсурский сандал",
    "pear leaf": "лист груши",
    "biscuit": "бисквит",
    "velvet": "бархат",
    "french orange flower": "французский цветок апельсина",
    "gourmand accord": "гурманский аккорд",
    "watercress": "водяной кресс",
    "mimosa absolute": "абсолют мимозы",
    "orange oil": "апельсиновое масло",
    "boronia": "боронния",
    "rhododendron": "рододендрон",
    "bellini": "беллини (коктейль)",
    "coriander leaf": "лист кориандра",
    "persimmon": "хурма",
    "chinese jasmine": "китайский жасмин",
    "timur": "тимур (перец)",
    "wallflower": "лакфиоль",
    "pomarose": "помароза",
    "coton candy": "сахарная вата",
    "linen": "льняное полотно",
    "breu-branco": "бреу-бранко",
    "olive blossom": "цветок оливы",
    "brazilian redwood": "бразильское красное дерево",
    "goji berries": "ягоды годжи",
    "monoi oil": "масло монои",
    "wild jasmine": "дикий жасмин",
    "tiramisu": "тирамису",
    "loukhoum": "лукум",
    "chinese cedar": "китайский кедр",
    "maple sap": "кленовый сок",
    "rain notes": "ноты дождя",
    "hinoki": "хиноки",
    "white magnolia": "белая магнолия",
    "sinfonide": "синфонид",
    "white lotus": "белый лотос",
    "indian saffron": "индийский шафран",
    "blue lavender": "голубая лаванда",
    "synthetic civet": "синтетический цибетин",
    "copal": "копал",
    "baie rose": "розовый перец (baie rose)",
    "kyara incense": "ладан кьяра",
    "juniper berry": "ягода можжевельника",
    "vetiver root": "корень ветивера",
    "aquatic notes": "водные ноты",
    "boysenberry": "бойзенова ягода",
    "white leather": "белая кожа",
    "french rose": "французская роза",
    "blue hyacinth": "синий гиацинт",
    "brazil nut": "бразильский орех",
    "mugane": "мугане",
    "pumpkin": "тыква",
    "exotic spices": "экзотические специи",
    "ambrofix™": "амброфикс™",
    "lime blossom": "цветок липы",
    "red amber": "красная амбра",
    "macadamia": "макадамия",
    "dulce de leche": "дульсе де лече",
    "yellow plum": "жёлтая слива",
    "ambertonic": "амбертоник",
    "raisin": "изюм",
    "heather": "вереск",
    "coconut blossom": "цветок кокоса",
    "agave": "агава",
    "black iris": "чёрный ирис",
    "mulberry": "тутовая ягода (шелковица)",
    "banana leaf": "банановый лист",
    "black leather": "чёрная кожа",
    "dyer’s greenweed": "дрок красильный",
    "ambrocenide": "амброценид",
    "syrup": "сироп",
    "cedar essence": "эссенция кедра",
    "blonde woods": "светлая древесина",
    "tonic water": "тоник",
    "vine": "виноградная лоза",
    "ash": "ясень",
    "vanilla sugar": "ванильный сахар",
    "co2 extracts": "CO2-экстракты",
    "pink nerium oleander": "розовый олеандр",
    "white ginger lily": "белая имбирная лилия",
    "pebbles": "галька",
    "pimento seeds": "семена пименто",
    "leatherwood": "лезеруд (кожаное дерево)",
    "lady of the night flower": "дама ночи (цеструм)",
    "oolong tea": "чай улун",
    "tomato": "томат",
    "red algae": "красные водоросли",
    "italian tangerine": "итальянский танжерин",
    "strawberry leaf": "лист клубники",
    "mirabilis": "мирабилис",
    "citrus": "цитрус",
    "nougat": "нуга",
    "paramela": "парамела",
    "californian lemon": "калифорнийский лимон",
    "coffee blossom": "цветок кофе",
    "flint": "кремень",
    "gray musk": "серый мускус",
    "palm tree": "пальма",
    "guarana": "гуарана",
    "transparent woods": "прозрачная древесина",
    "panacotta": "панна-котта",
    "blue sage": "голубой шалфей",
    "ginseng": "женьшень",
    "nettle": "крапива",
    "peat": "торф",
    "marmalade": "мармелад",
    "florida grapefruit": "флоридский грейпфрут",
    "thuja": "туя",
    "campari": "кампари",
    "galanga": "галангал",
    "mushroom": "гриб",
    "karo karounde": "каро каронде",
    "maninka": "манинка",
    "hyssop": "иссоп",
    "finger lime": "пальчиковый лайм",
    "reed": "тростник",
    "oak tree": "дуб",
    "limoncello": "лимончелло",
    "plum tree": "слива (дерево)",
    "citrus blossom": "цветок цитруса",
    "nerium oleander": "олеандр",
    "tequila": "текила",
    "ishpink": "ишпинк",
    "ocotea quixos": "окотея",
    "liquidambar": "ликвидамбар",
    "barley": "ячмень",
    "strelitzia": "стрелиция",
    "indian vanilla": "индийская ваниль",
    "olive": "олива",
    "egyptian pelargonium": "египетская пеларгония",
    "sylkolide": "силколид",
    "ambrox super": "амброкс супер",
    "floral fruity notes": "цветочно-фруктовые ноты",
    "jackfruit": "джекфрут",
    "apple tree blossom": "цветение яблони",
    "larch": "лиственница",
    "african ginger": "африканский имбирь",
    "bergamot leaf": "лист бергамота",
    "egyptian musk": "египетский мускус",
    "blue rose": "синяя роза",
    "massoia": "массоя",
    "plumeria": "плюмерия",
    "butterfly orchid": "орхидея-бабочка",
    "italian cypress": "итальянский кипарис",
    "white wine": "белое вино",
    "calypsone": "калипсон",
    "iced lemon": "ледяной лимон",
    "vermouth": "вермут",
    "chinese peony": "китайский пион",
    "lactones": "лактоны",
    "orangewood": "апельсиновое дерево",
    "asphalt": "асфальт",
    "pitanga": "питанга",
    "citrus leaf": "лист цитруса",
    "oriental woodsy notes": "восточные древесные ноты",
    "martini": "мартини",
    "rooibos tea": "чай ройбуш",
    "gunpowder": "порох",
    "flower petals": "лепестки цветов",
    "wild lavender": "дикая лаванда",
    "light amber": "светлая амбра",
    "egyptian balsam": "египетский бальзам",
    "pepperwood or hercules club": "перечное дерево (геркулесова дубина)",
    "peppertree": "перечное дерево",
    "curry tree": "карри дерево",
    "flax": "лён",
    "karo-korund": "каро-корунд",
    "candied orange": "засахаренный апельсин",
    "marron glace": "марон гласе",
    "indian ginger": "индийский имбирь",
    "barberry": "барбарис",
    "pear wood": "грушевое дерево",
    "boletus edulis": "белый гриб",
    "indole": "индол",
    "honeycomb": "медовые соты",
    "bubble gum": "жевательная резинка",
    "clove leaf": "лист гвоздики",
    "mock orange": "жасмин садовый (чубушник)",
    "henna": "хна",
    "javanol": "джаванол",
    "papaya flower": "цветок папайи",
    "citrus leaves": "листья цитруса",
    "lotus leaf": "лист лотоса",
    "champagne rosé": "розовое шампанское",
    "sweet grass": "сладкая трава (зубровка)",
    "natural vanilla": "натуральная ваниль",
    "cedarmoss": "кедровый мох",
    "iris petals": "лепестки ириса",
    "buddleia": "будлея",
    "silver fir": "пихта серебристая",
    "green lilac": "зелёная сирень",
    "prunella": "черноголовка",
    "chinese cinnamon wood": "китайская коричная древесина",
    "cypress leaf": "лист кипариса",
    "rice basmati": "рис басмати",
    "soybean": "соя",
    "cherry liqueur": "вишнёвый ликёр",
    "pandanus": "пандан",
    "bergamot blossom": "цветок бергамота",
    "safraleine": "сафралеин",
    "pimento leaf": "лист пименто",
    "cedar leaves": "листья кедра",
    "cassia bourbon": "бурбонская кассия",
    "spanish jasmine": "испанский жасмин",
    "vanillin": "ванилин",
    "boxwood": "самшит",
    "desert rose": "роза пустыни",
    "indian spices": "индийские специи",
    "nectarine blossom": "цветок нектарина",
    "bourbon whiskey": "бурбон",
    "red sandalwood": "красный сандал",
    "cloudberry": "морошка",
    "storax": "стиракс",
    "lydia broom": "лидийский дрок",
    "cherry extract": "экстракт вишни",
    "water flowers": "водные цветы",
    "lime peel": "цедра лайма",
    "massoia wood": "массойя",
    "madagascar cloves": "мадагаскарская гвоздика",
    "sicilian citruses": "сицилийские цитрусы",
    "rubber": "резина",
    "african violet": "африканская фиалка (сенполия)",
    "pear ice cream": "грушевое мороженое",
    "snow": "снег",
    "confetti (sugared almonds)": "конфетти (засахаренный миндаль)",
    "primrose": "примула",
    "wasabi": "васаби",
    "nutty notes": "ореховые ноты",
    "green mango": "зелёное манго",
    "ground cherry": "физалис",
    "black locust honey": "мёд белой акации",
    "pineapple blossom": "цветок ананаса",
    "pink lily": "розовая лилия",
    "plum wood": "слива (дерево)",
    "red litchi": "красный личи",
    "olive leaf": "лист оливы",
    "star apple": "стар-эппл (хризофиллум)",
    "rangoon creeper": "комбретум",
    "chinotto": "кинотто",
    "black licorice": "чёрная солодка",
    "valerian": "валериана",
    "chocolate flower": "цветок шоколада (кошения)",
    "mandora": "мандора",
    "pink litchi": "розовый личи",
    "italian violet": "итальянская фиалка",
    "japanese osmanthus": "японский османтус",
    "edelweiss": "эдельвейс",
    "stems greens": "зелёные стебли",
    "soap": "мыло",
    "lantana": "лантана",
    "yellow narcissus": "жёлтый нарцисс",
    "mirabella plum": "слива мирабель",
    "ambretone": "амбретон",
    "hellebore flower": "цветок морозника",
    "cilantro": "кинза",
    "aquozone": "акуозон",
    "tangerine blossom": "цветок мандарина",
    "tahitian gardenia": "таитянская гардения",
    "guava blossom": "цветок гуавы",
    "pansy": "анютины глазки",
    "yellow fruits": "жёлтые фрукты",
    "blackberry blossom": "цветок ежевики",
    "candied ginger": "засахаренный имбирь",
    "wood resin": "древесная смола",
    "clay": "глина",
    "green anjou pears": "зелёные груши анжу",
    "mahonia": "магония",
    "japanese loquat": "японская мушмула (локва)",
    "hamanasu or japanese rose": "хамаsu (японская роза)",
    "evernyl": "эвернил",
    "rosebay willowherb": "иван-чай",
    "pepper oil": "перечное масло",
    "french narcissus": "французский нарцисс",
    "pepperwood™": "перечное дерево™",
    "red currant leaf": "лист красной смородины",
    "muscenone": "мусценон",
    "fire": "огонь",
    "poplar (populus) buds": "почки тополя",
    "jabuticaba": "жаботикаба",
    "kulfi": "кульфи (мороженое)",
    "black basil": "чёрный базилик",
    "genet": "ракитник (genet)",
    "betel pepper": "бетелевый перец",
    "mandarin": "мандарин",
    "cachaça": "кашаса",
    "gorse": "утёсник",
    "geosmin": "геосмин",
    "iran galbanum": "иранский гальбанум",
    "argentinian lemon": "аргентинский лимон",
    "fuchsia": "фуксия",
    "helvetolide": "гельветолид",
    "hot iron": "горячий утюг",
    "sour cherry blossom": "цветок вишни",
    "indian mandarin": "индийский мандарин",
    "hog plum": "слива дикая (hog plum)",
    "milk chocolate": "молочный шоколад",
    "beetroot": "свёкла",
    "red tea": "красный чай",
    "coal": "уголь",
    "white pear": "белая груша",
    "yellow rose": "жёлтая роза",
    "maraschino cherry": "вишня мараскино",
    "curacao": "кюрасао",
    "sand lily": "песчаная лилия",
    "japanese plum": "японская слива",
    "dandelion": "одуванчик",
    "green tangerine": "зелёный мандарин",
    "rose mallow": "розовая мальва",
    "white heliotrope": "белый гелиотроп",
    "california orange": "калифорнийский апельсин",
    "white hyacinth": "белый гиацинт",
    "bigarade": "бигарад (горький апельсин)",
    "sycamore": "сикомора",
    "jasmine leaf": "лист жасмина",
    "lysylang": "лисиланг",
    "methyl pamplemousse": "метилпампльмус",
    "tangelo": "танжело",
    "scent trek®": "scent trek®",
    "yogurt": "йогурт",
    "dill": "укроп",
    "grape leaves": "виноградные листья",
    "jacaranda": "жакаранда",
    "diamond orchid": "алмазная орхидея",
    "wine lees": "винный осадок",
    "white carnation": "белая гвоздика",
    "georgywood": "джорджвуд",
    "banana flower": "цветок банана",
    "iris butter": "масло ириса",
    "dihydromyrcenol": "дигидромирценол",
    "santolina": "сантолина",
    "cyperus esculentus": "чуфа",
    "laburnum": "ракитник золотой дождь",
    "parsley": "петрушка",
    "apple leaf": "яблочный лист",
    "tansy": "пижма",
    "hazelnut cocoa spread": "ореховая шоколадная паста",
    "almond cream": "миндальный крем",
    "pine tar": "сосновый дёготь",
    "cacao butter": "масло какао",
    "bulrush": "камыш",
    "thanaka wood": "дерево танака",
    "daim": "даим",
    "mayflower": "майский цветок",
    "brazilian mandarin": "бразильский мандарин",
    "mousse de saxe": "мусс де сакс",
    "silkwood blossom": "цветок шёлкового дерева",
    "indonesian jasmine": "индонезийский жасмин",
    "white rum": "белый ром",
    "white tabacco": "белый табак",
    "balsamic vinegar": "бальзамический уксус",
    "cashew": "кешью",
    "lemon balm": "мелисса",
    "crithmum": "критмум (морской укроп)",
    "wild strawberry leaf": "лист лесной земляники",
    "kir royal": "кир рояль",
    "coriander extract": "экстракт кориандра",
    "creosote bush": "креозотовый куст",
    "french violet": "французская фиалка",
    "coral reef": "коралловый риф",
    "rosa rubiginosa": "роза ругоза",
    "khella": "хелла",
    "pomegranate blossom": "цветок граната",
    "beech": "бук",
    "pea": "горошек",
    "lemonade": "лимонад",
    "greengage": "ренклод (слива)",
    "tea tree oil": "масло чайного дерева",
    "white camelia": "белая камелия",
    "fruity": "фруктовый",
    "pink hyacinth": "розовый гиацинт",
    "cobblestone": "булыжник",
    "norlimbanol™": "норлимбанол™",
    "iced tea": "холодный чай",
    "cosmone": "космон",
    "oat": "овёс",
    "propolis": "прополис",
    "belambra tree": "беламбра",
    "ho wood": "дерево хо",
    "sweet pepper": "сладкий перец",
    "french pastries": "французская выпечка",
    "princess tree or paulownia": "павловния",
    "silk": "шёлк",
    "calissons d'aix": "калиссоны из экса",
    "myrrh oil": "масло мирры",
    "indian pepper": "индийский перец",
    "madagascar sandalwood": "мадагаскарский сандал",
    "suntan lotion": "лосьон для загара",
    "saffiano leather": "кожа сафьяно",
    "cottonwood (poplar)": "тополь",
    "periwinkle": "барвинок",
    "icing pink": "розовая глазурь",
    "sea buckthorn": "облепиха",
    "rose leaf": "лист розы",
    "yellow water lily": "жёлтая кубышка",
    "white nerium oleander": "белый олеандр",
    "red peach": "красный персик",
    "white almond": "белый миндаль",
    "rice flower": "цветок риса",
    "reseda": "резеда",
    "hemlock": "болиголов",
    "peanut": "арахис",
    "lichen": "лишайник",
    "chinese plum": "китайская слива",
    "green lily": "зелёная лилия",
    "white cyclamen": "белый цикламен",
    "hivernal®": "hivernal®",
    "rose oxide": "оксид розы",
    "moroccan lemon": "марокканский лимон",
    "forget me not": "незабудка",
    "grapefruit leaf": "лист грейпфрута",
    "blackberry leaf": "лист ежевики",
    "dragon blood resin": "смола драконова дерева",
    "yellow champaca": "жёлтая чампака",
    "lotus petals": "лепестки лотоса",
    "melilot or sweet clover": "донник",
    "bourbon rose": "бурбонская роза",
    "somalian opoponax": "сомалийский опопонакс",
    "ginger leaf": "лист имбиря",
    "cereals": "злаки",
    "elm": "вяз",
    "roasted nuts": "жареные орехи",
    "daiquiri": "дайкири",
    "arnica": "арника",
    "chinese black tea": "китайский чёрный чай",
    "tayberry": "тейберри",
    "chinese orange": "китайский апельсин",
    "egyptian sage": "египетский шалфей",
    "white mimosa": "белая мимоза",
    "bay essence": "эссенция лавра",
    "baobab": "баобаб",
    "bougainvillea": "бугенвиллея",
    "cananga": "кананга",
    "israeli basil": "израильский базилик",
    "bluebell": "колокольчик лесной",
    "milk cream": "молочные сливки",
    "pinot noir grapes": "виноград пино нуар",
    "red freesia": "красная фрезия",
    "canadian balsam": "канадский бальзам",
    "erigeron (fleabane)": "мелколепестник",
    "fig wood bark": "кора инжирного дерева",
    "orchid pink leopard": "орхидея розовый леопард",
    "laminaria": "ламинария",
    "white bergamot": "белый бергамот",
    "soursop": "соусоп (гравиола)",
    "chinese tea": "китайский чай",
    "masala chai": "масала чай",
    "hibiscus blossom": "цветок гибискуса",
    "columbian coffee": "колумбийский кофе",
    "choya loban": "чойя лобан",
    "cactus juice": "сок кактуса",
    "choya nakh": "чойя нах",
    "prunol": "пранол",
    "lipstick": "губная помада",
    "seashells": "морские раковины",
    "black hemlock or tsuga": "чёрная тсуга",
    "citruses water": "цитрусовая вода",
    "iris leaf": "лист ириса",
    "hatkora lemon": "лимон хаткора",
    "head space waterfall": "ноты водопада",
    "blood": "кровь",
    "dark patchouli": "тёмная пачули",
    "juicy apricot": "сочный абрикос",
    "green pear": "зелёная груша",
    "frosted berries": "ягоды в инее",
    "creamy flowers": "сливочные цветы",
    "aqual": "аквал",
    "pamplewood": "пампльвуд",
    "cypriol": "циприол",
    "goldenrod": "золотарник",
    "ginkgo": "гинкго",
    "safflower": "сафлор",
    "american apple": "американское яблоко",
    "sake": "саке",
    "egyptian tuberose": "египетская тубероза",
    "sicilian citrus": "сицилийский цитрус",
    "italian melon": "итальянская дыня",
    "bread": "хлеб",
    "canadian fir": "канадская пихта",
    "white willow": "белая ива",
    "coffee co2": "кофе CO2",
    "cubeb or tailed pepper": "кубеба (хвостатый перец)",
    "cascarilla": "кaскарилла",
    "borage": "бораго",
    "violet woodsorrel": "кислица фиолетовая",
    "slate": "сланец",
    "moscow mule": "москоу мул",
    "plastic": "пластик",
    "gasoline": "бензин",
    "neoprene": "неопрен",
    "limewood": "липовая древесина",
    "black gardenia": "чёрная гардения",
    "rye": "рожь",
    "himalayan poppy": "гималайский мак",
    "angels trumpet": "дурман (труба ангела)",
    "white cardamom": "белый кардамон",
    "freesia petals": "лепестки фрезии",
    "red fruits sorbet": "сорбет из красных ягод",
    "ravensara": "равенсара",
    "poinsettia": "пуансеттия",
    "cashalox": "кашалокс",
    "punch": "пунш",
    "agave nectar": "нектар агавы",
    "water violet": "водная фиалка",
    "bark": "кора",
    "dianthus": "гвоздика садовая",
    "privet": "бирючина",
    "peruvian pepper": "перуанский перец",
    "brioche": "бриошь",
    "croissant": "круассан",
    "wild peony": "дикий пион",
    "mitti attar": "митти аттар",
    "orange cassia tree": "апельсиновая кассия",
    "red myrrh": "красная мирра",
    "prickly pear": "опунция",
    "iris pallida": "ирис бледный",
    "coranol": "коранол",
    "zinnia": "циния",
    "corall orchid": "коралловая орхидея",
    "damascone": "дамаскон",
    "fig blossom": "цветок инжира",
    "teakwood essence": "эссенция тика",
    "buttercup": "лютик",
    "pelargonium leaf": "лист пеларгонии",
    "lilybelle®": "lilybelle®",
    "darjeeling tea": "чай дарджилинг",
    "fabric": "ткань",
    "aglaia": "аглайя",
    "red cyclamen": "красный цикламен",
    "varnish accord": "лаковый аккорд",
    "althaea": "алтей",
    "pink violet": "розовая фиалка",
    "galbanum leaf": "лист гальбанума",
    "egyptian rose": "египетская роза",
    "pink paprika": "розовая паприка",
    "almond wood": "миндальное дерево",
    "talc": "тальк",
    "mariposa lily": "марипоса лилия",
    "mystikal": "мистикал",
    "vietnamese oud": "вьетнамский уд",
    "red currant blossom": "цветок красной смородины",
    "apple juice": "яблочный сок",
    "williams pear": "груша вильямс",
    "turnera diffusa (damiana)": "дамиана",
    "hinoki incense": "благовоние хиноки",
    "kyphi": "кифи",
    "carob tree": "рожковое дерево",
    "sicilian bitter orange": "сицилийский горький апельсин",
    "carnation leaves": "листья гвоздики",
    "garden dill": "садовый укроп",
    "cornflower or sultan seeds": "василёк",
    "calamansi": "каламанси",
    "green orange": "зелёный апельсин",
    "cherry tree": "вишнёвое дерево",
    "silk vine or milk broom": "ваточник (silk vine)",
    "red tulip": "красный тюльпан",
    "green coriander": "зелёный кориандр",
    "nympheal™": "нимфеал™",
    "cork": "пробка",
    "guaiacol": "гваякол",
    "magnolan": "магнолан",
    "water pepper": "водяной перец",
    "snowberry": "снежноягодник",
    "cherimoya": "черимойя",
    "ambrostar™": "амбростар™",
    "toscanol": "тосканол",
    "kephalis": "кефалис",
    "rose jam": "розовый джем",
    "green tea flower": "цветок зелёного чая",
    "curry": "карри",
    "chinese patchouli": "китайская пачули",
    "amazon lily": "амазонская лилия",
    "eucalyptus blossom": "цветок эвкалипта",
    "black diamond": "чёрный алмаз",
    "lip gloss": "блеск для губ",
    "blue curacao": "голубой кюрасао",
    "chimonanthus or wintersweet": "химонант (зимоцвет)",
    "buddha wood": "дерево будды",
    "orange pepper": "оранжевый перец",
    "salicylic acid": "салициловая кислота",
    "silver pine": "серебристая сосна",
    "california redwood": "калифорнийская секвойя",
    "egyptian rosewood": "египетское розовое дерево",
    "yarrow": "тысячелистник",
    "mimosa leaves": "листья мимозы",
    "indonesian carnation": "индонезийская гвоздика",
    "cocobolo": "кокоболо",
    "mangosteen blossom": "цветок мангостина",
    "pomegranate seed": "зерно граната",
    "thistle": "чертополох",
    "argan": "аргана",
    "flouve": "флуве (душистый колосок)",
    "frosted apple": "яблоко в инее",
    "belladonna": "белладонна",
    "loganberry": "логанова ягода",
    "chinese grapefruit": "китайский грейпфрут",
    "ambreine": "амбреин",
    "opium": "опиум",
    "japanese cypress": "японский кипарис (хиноки)",
    "assam oud": "ассамский уд",
    "serenolide": "серенолид",
    "nettle blossom": "цветок крапивы",
    "vanilla caviar": "ванильная икра",
    "portulaca or pigweed": "портулак",
    "pollen": "пыльца",
    "pancake": "блин (панкейк)",
    "california cedar": "калифорнийский кедр",
    "transparent flowers": "прозрачные цветы",
    "musk vodka": "мускусная водка",
    "basil leaf": "лист базилика",
    "lapsang souchong tea": "чай лапсанг сушонг",
    "woodruff or galium odoratum": "ясменник пахучий",
    "frosted orange": "апельсин в инее",
    "chinese litchi": "китайский личи",
    "lemon leaf oil": "масло лимонного листа",
    "asian lily": "азиатская лилия",
    "cosmos flower": "цветок космеи",
    "rhum agricole": "ромовая дистилляция (агриколь)",
    "frosted melon": "дыня в инее",
    "avocado": "авокадо",
    "calycanthus": "каликантус",
    "fruit tea": "фруктовый чай",
    "tulsi": "тулси",
    "bulgarian light tobacco": "болгарский светлый табак",
    "kaffir lime": "лайм каффир",
    "amber oil": "амбровое масло",
    "white ginger": "белый имбирь",
    "sideritis": "сидеритис (горный чай)",
    "mountain tea": "горный чай",
    "nigerian ginger": "нигерийский имбирь",
    "serbian oakmoss": "сербский дубовый мох",
    "hazel bloosom": "цветок лещины",
    "satureja": "чабер",
    "daphne": "дафна (волчеягодник)",
    "redwood flower": "цветок секвойи",
    "muhuhu": "мухуху",
    "mango tree": "дерево манго",
    "wild orange": "дикий апельсин",
    "liv tyler rose": "роза лив тайлер",
    "indonesian myrrh": "индонезийская мирра",
    "panettone": "панеттоне",
    "australian blue cypress": "австралийский голубой кипарис",
    "tomato flower": "цветок томата",
    "spearmint": "мята кудрявая",
    "corn": "кукуруза",
    "concrete": "бетон",
    "chive": "зелёный лук (chive)",
    "dried apricot": "курага",
    "vanilla leaves": "листья ванили",
    "ultravanil™": "ультраванил™",
    "white peach blossom": "цветок белого персика",
    "azalea": "азалия",
    "bubbaloo": "баблало",
    "dark plum wu mei": "тёмная слива (умэй)",
    "oriental flower notes": "восточные цветочные ноты",
    "coffee tincture": "настойка кофе",
    "saw palmetto": "пальма сереноа",
    "linaloe berry": "ягода линалоэ",
    "yohimbe": "йохимбе",
    "spray paint": "аэрозольная краска",
    "sarsaparilla": "сарсапарилла",
    "skeleton flower (diphylleia grayi)": "скелетный цветок (диффилея)",
    "liatrix": "лиатрис",
    "eglantine rose": "шиповник (роза эглантерия)",
    "oysters": "устрицы",
    "ravenala": "равенала",
    "bonbon": "конфета (бонбон)",
    "aluminum": "алюминий",
    "red willow": "красная ива",
    "fringed pink": "гвоздика бородатая",
    "alyssum": "алиссум",
    "frosted mango": "манго в инее",
    "indian lotus": "индийский лотос",
    "wisteria flower": "цветок глицинии",
    "butomus umbellatus": "сусак зонтичный",
    "st. john's wort": "зверобой",
    "valencia orange flower": "цветок апельсина валенсия",
    "tuscan cypress": "тосканский кипарис",
    "hoary stock": "маттиола (левкой)",
    "jelly": "желе",
    "island musk": "островной мускус",
    "lamprocapnos": "дицентра",
    "steam accord": "паровой аккорд",
    "indonesian pepper": "индонезийский перец",
    "english rose": "английская роза",
    "red nectarine": "красный нектарин",
    "arctic bramble": "поляника (арктическая малина)",
    "iodine": "йод",
    "terranol": "терранол",
    "medlar": "мушмула",
    "karmaflor®": "karmaflor®",
    "nard": "нард",
    "trimofix®": "trimofix®",
    "christmas tree or flame tree": "новогодняя ель",
    "mistletoe": "омела",
    "cream soda": "крем-сода",
    "fish": "рыба",
    "grape seed": "виноградная косточка",
    "chinese apricot": "китайский абрикос",
    "moroccan mimosa": "марокканская мимоза",
    "black pomegranate": "чёрный гранат",
    "caoutchouc": "каучук",
    "stone": "камень",
    "apple mint": "яблочная мята",
    "ducke": "дюк",
    "ornithogalum": "птицемлечник",
    "japanese orchid": "японская орхидея",
    "rangpur": "рангпур",
    "indian woods": "индийская древесина",
    "white cherry": "белая вишня",
    "polygonum": "горец (polygonum)",
    "green coconut": "зелёный кокос",
    "araucaria": "araucaria",
    "chinese pink peony": "китайский розовый пион",
    "longan berries": "лонган",
    "play-doh": "пластилин",
    "green orchid": "зелёная орхидея",
    "californian gardenia": "калифорнийская гардения",
    "african freesia petals": "лепестки африканской фрезии",
    "fig honey": "инжирный мёд",
    "sweat": "пот",
    "indian white pepper": "индийский белый перец",
    "yellow flowers": "жёлтые цветы",
    "moepel accord": "аккорд моепель",
    "nail polish": "лак для ногтей",
    "eau de vie": "о-де-ви (фруктовый бренди)",
    "surf wax": "сёрф-воск",
    "burnt match": "сгоревшая спичка",
    "graphite": "графит",
    "japanese orange": "японский апельсин",
    "cassowary fruit": "плод казуарины",
    "white datura": "белый дурман",
    "kyoto rose petals": "лепестки розы киото",
    "moon flower": "лунный цветок",
    "buckwheat tea": "гречишный чай",
    "japanese pepper": "японский перец",
    "sainfoins": "эспарцет",
    "cosmopolitan cocktail": "коктейль космополитан",
    "pearadise®": "pearadise®",
    "water peony": "водный пион",
    "solomon's seal": "купена",
    "crinum lily": "кринум",
    "bigarane™": "bigarane™",
    "oak leaves": "дубовые листья",
    "royal lily": "королевская лилия",
    "myrica": "мирика",
    "coca": "кока",
    "hollyhock": "штокроза (мальва)",
    "angelica root": "корень дудника",
    "moroccan": "марокканский",
    "rose thorn": "шип розы",
    "vanilla bahiana": "ваниль баия",
    "coffee tree": "кофейное дерево",
    "rambutan": "рамбутан",
    "pisco sour cocktal": "коктейль писко сауэр",
    "green sap": "зелёный сок",
    "hexyl acetate": "гексилацетат",
    "vinyl guaiacol": "винилгваякол",
    "sp3 carbon": "sp3-углерод",
    "white royal lily": "белая королевская лилия",
    "rosa alba": "роза альба",
    "rice leaf": "лист риса",
    "japanese gardenia": "японская гардения",
    "madeira": "мадера",
    "sodium silicate": "силикат натрия",
    "japanese pink lotus": "японский розовый лотос",
    "cupuacu": "купуасу",
    "cupuassu": "купуасу",
    "copoasu": "купуасу",
    "citruses with sugar": "цитрусы с сахаром",
    "belanis": "беланис",
    "french hyacinth": "французский гиацинт",
    "georgian apricot": "грузинский абрикос",
    "pink crystal": "розовый кристалл",
    "white honeysuckle": "белая жимолость",
    "firwood": "пихтовая древесина",
    "prosecco": "просекко",
    "grass tree": "травяное дерево (ксанторрея)",
    "red vanill-orchid": "красная ванильная орхидея",
    "caipirinha": "кайпиринья",
    "fresh almond": "свежий миндаль",
    "hawaiian fruits": "гавайские фрукты",
    "indian mimosa": "индийская мимоза",
    "sangria": "сангрия",
    "fougassette": "фугассетта",
    "wisteria petals": "лепестки глицинии",
    "cacao blossom": "цветок какао",
    "orchard blossom": "цветение сада",
    "blue margarita": "голубая маргарита (коктейль)",
    "zefir": "зефир",
    "gustavia flower": "цветок густавии",
    "calla lily": "калла",
    "physcool®": "physcool®",
    "cep": "белый гриб (cep)",
    "dodecanal": "додеканал",
    "choya ral": "чойя рал",
    "wolfberry": "годжи (волчья ягода)",
    "butterscotch": "ириска (баттерскотч)",
    "laurissilva forest": "лаврисильва (лес)",
    "peyote": "пейот",
    "rice pudding": "рисовый пудинг",
    "yuzu flower": "цветок юзу",
    "daylily": "лилейник",
    "jade flower": "цветок нефрита",
    "azteca lily": "лилия ацтека",
    "sapodilla": "сапота",
    "instant film accord": "аккорд мгновенного фото",
    "acetylfuran": "ацетилфуран",
    "burning cherry": "горящая вишня",
    "factor x": "фактор икс",
    "plum wine": "сливовое вино",
    "indian tea": "индийский чай",
    "lava": "лава",
    "white chocolate truffle": "трюфель из белого шоколада",
    "pearls": "перламутр",
    "mai tai cocktail": "коктейль май тай",
    "jasmolactone": "жасмолактон",
    "jellybean": "жевательная конфета",
    "gladiolus": "гладиолус",
    "japanese green tea": "японский зелёный чай",
    "chocolate truffle": "шоколадный трюфель",
    "sea daffodil": "морской нарцисс",
    "western skunk cabbage": "лизихитон",
    "canadian pine": "канадская сосна",
    "white blossom": "белый цвет (цветение)",
    "citron leaf": "лист цитрона",
    "tucumã": "тукума",
    "sparkling wine": "игристое вино",
    "trees": "деревья",
    "molasses": "патока (молассы)",
    "protea": "протея",
    "sulphur": "сера",
    "gianduia": "джандуйя",
    "satinwood": "атласное дерево",
    "arbutus (madrona": "земляничное дерево (мадрона)",
    "bearberry tree)": "медвежья ягода (дерево)",
    "ditax wood": "дитакс",
    "chocolate fudge": "шоколадная помадка",
    "baileys irish cream": "бейлис (ликёр)",
    "geranium macrorrhizum (zdravetz)": "здравец (герань крупнокорневая)",
    "malaysian oud": "малазийский уд",
    "applejack": "яблочный бренди",
    "starfish": "морская звезда",
    "blueberry leaf": "лист черники",
    "ember": "тлеющие угли",
    "campion flower": "смолка (campion)",
    "rumex": "щавель",
    "gold": "золото",
    "red maple": "красный клён",
    "grapefruit peel": "цедра грейпфрута",
    "chayote": "чайот",
    "tamarisk": "тамариск",
    "ouzo": "узо",
    "elderberry": "бузина",
    "gerbera": "гербера",
    "candied lemon": "засахаренный лимон",
    "peach cream": "персиковый крем",
    "floral bouquet": "цветочный букет",
    "turkish coffee beans": "зёрна турецкого кофе",
    "snake plant": "сансевиерия",
    "roots": "корни",
    "macchiato": "макиато",
    "chutney": "чатни",
    "virginian patchouli": "виргинская пачули",
    "coconut leaf": "кокосовый лист",
    "cinnamon flower": "цветок корицы",
    "antillone™": "антиллон™",
    "gariguette strawberry": "клубника гаригетт",
    "hat straw": "соломенная шляпа",
    "breadnut": "хлебное дерево (бреднат)",
    "black clover": "чёрный клевер",
    "capitiú": "капитиу",
    "red mulberry": "красная шелковица",
    "rosebud": "бутон розы",
    "pistachio blossom": "цветок фисташки",
    "genipapo": "женипапо",
    "strawberry syrup": "клубничный сироп",
    "green lotus": "зелёный лотос",
    "darjeeling black tea": "чёрный чай дарджилинг",
    "walnut milk": "ореховое молоко",
    "buttercream": "крем масляный",
    "cookie": "печенье",
    "siam resin": "сиамская смола",
    "dried rose": "сушёная роза",
    "palestinian sweet lime": "палестинский сладкий лайм",
    "green forest": "зелёный лес",
    "nutella": "нутелла",
    "halva": "халва",
    "siam": "сиам",
    "st": "—",
    "white dahlia": "белый георгин",
    "poivrol": "пуавроль",
    "cheesecake": "чизкейк",
    "jujube blossom": "цветок зизифуса (унаби)",
    "texas rosewood": "техасское розовое дерево",
    "rose juliette greco": "роза джульетт греко",
    "californian fig": "калифорнийский инжир",
    "ravello rose": "роза равелло",
    "sandalwood flower": "цветок сандала",
    "hassaku": "хассаку",
    "shea nuts": "орехи ши",
    "white tea blossom": "цветок белого чая",
    "limnophila aromatica": "лимнофила ароматная (рисовый кориандр)",
    "red fruits smoothie": "смузи из красных ягод",
    "nag champa": "наг чампа",
    "starflower": "звёздчатый цветок (бораго)",
    "mocha": "мокко",
    "paperbark": "бумажная кора (мелалеука)",
    "siam wood": "сиамское дерево",
    "durian": "дуриан",
    "cherry milk": "вишнёвое молоко",
    "impatiens": "недотрога (бальзамин)",
    "beer/ale": "пиво (эль)",
    "wet plaster": "мокрая штукатурка",
    "white mimosa honey": "мёд белой мимозы",
    "kiwi flower": "цветок киви",
    "chinotto blossom": "цветок кинотто",
    "industrial glue": "промышленный клей",
    "brown scotch tape": "коричневый скотч",
    "orange honey": "апельсиновый мёд",
    "malva": "мальва",
    "shamama attar": "шамама аттар",
    "algerian geranium": "алжирская герань",
    "lantana leaves": "листья лантаны",
    "buriti": "бурити",
    "acerola blossom": "цветок ацеролы",
    "field scabious": "короставник",
    "milkshake": "молочный коктейль",
    "yellow poppy": "жёлтый мак",
    "orchid black diamond": "орхидея чёрный алмаз",
    "canada balsam": "канадский бальзам",
    "sumac": "сумах",
    "melissa flower": "цветок мелиссы",
    "shiikuwasha": "шиикуваша",
    "roselle": "розелла (гибискус)",
    "coral limestone": "коралловый известняк",
    "gajumaru banyan": "баньян гаджумару",
    "mugwort": "полынь обыкновенная",
    "carambola blossom": "цветок карамболы",
    "toast": "тост",
    "cookie dough": "тесто для печенья",
    "sclarene": "склaрен",
    "pistachio leaf": "лист фисташки",
    "katsura leaf": "лист кацуры",
    "holly flower": "цветок падуба",
    "mimosa petals": "лепестки мимозы",
    "bengal pepper": "бенгальский перец",
    "cocoa": "какао",
    "artichoke": "артишок",
    "feijoa fruit": "фейхоа",
    "petroleum": "нефть",
    "seriguela": "сериgуэла",
    "frosting [glacé]": "глазурь",
    "green nard": "зелёный нард",
    "mascarpone cheese": "маскарпоне",
    "alumroot": "гейхера",
    "mezcal": "мескаль",
    "canelé": "канеле",
    "indian mango": "индийское манго",
    "mamey": "мамей",
    "golden lily": "золотая лилия",
    "naturalcalm™": "натуралкалм™",
    "bearberry": "толокнянка",
    "orange blossom absolute": "абсолют цветка апельсина",
    "watery cyclamen": "водянистый цикламен",
    "chinese oud": "китайский уд",
    "dove tree": "давидия (голубиное дерево)",
    "linden blossom": "цветок липы",
    "lupin": "люпин",
    "soy milk": "соевое молоко",
    "taro": "таро",
    "lemon soda": "лимонная сода",
    "tulle accord": "тюлевый аккорд",
    "cocktail fruits": "коктейльные фрукты",
    "kopi luwak coffee": "кофе копи лювак",
    "muskrat": "мускусная крыса (ондатра)",
    "pink flamingo heliconia": "геликония розовый фламинго",
    "spinach": "шпинат",
    "katrafay": "катрафай",
    "carambola": "карамбола",
    "alpinia": "альпиния",
    "bakhoor": "бахур",
    "bushman candle": "свеча бушмена",
    "lychee": "личи",
    "coral amber": "коралловая амбра",
    "cake": "торт",
    "limetta": "лиметта",
    "boozy notes": "алкогольные ноты",
    "cantaloupe": "канталупа",
    "blackcurrant": "чёрная смородина",
    "acerola": "ацерола",
    "kadam": "кадам",
    "moroccan jasmine": "марокканский жасмин",
    "paper": "бумага",
    "vinyl": "винил",
}
